config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'main#index'
  get 'about_us' => 'about_us#index', :as => 'about_us'
  get 'news' => 'news#index', :as => 'news'
  get 'work' => 'work#index', :as => 'work'
  get 'work/:id' => 'work#show', :as => 'work_show'
  get 'services' => 'services#index', :as => 'services'
  get 'qa' => 'qa#index', :as => 'qa'
  get 'qa/:id' => 'qa#show', :as => 'qa_show'
  get 'contact_us' => 'contact_us#index', :as => 'contact_us'
 

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :works
	accepts_nested_attributes_for :works, allow_destroy: true

	rails_admin do
        list do
        	field :id do
        		label "ID"
        	end	
            field :name
            field :updated_at do
           		strftime_format '%Y-%m-%d'
            end
            field :created_at do
           		strftime_format '%Y-%m-%d'
            end
        end

        edit do
            field :name
        end
    end		
end

app/models/qa.rb
class Qa < ActiveRecord::Base
    rails_admin do
        list do
            field :id do
                label "ID"
            end 
            field :question
            field :answer
            field :updated_at do
                strftime_format '%Y-%m-%d'
            end
            field :created_at do
                strftime_format '%Y-%m-%d'
            end
        end

        edit do
            field :question
            field :answer
        end
    end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
	rails_admin do
        list do
        	field :email do
        		label "信箱"
        	end	
            field :sign_in_count do
            	label "登入次數"
            end	
            field :last_sign_in_at do
            	label "上次登入時間"
           		strftime_format '%Y-%m-%d'
            end
        end

        edit do
        	field :email do
        		label "信箱"
        	end	
            field :password do
            	label "密碼"
            end	
        end
    end	  
end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :category
	has_many :work_pics
	accepts_nested_attributes_for :work_pics, allow_destroy: true

    paginates_per 6

    def first_photo
        self.work_pics.first
    end

	rails_admin do
        list do
            field :title
            field :description
            field :created_at do
           		strftime_format '%Y-%m-%d'
            end
            field :work_pics 
        end

        edit do
        	field :category do
                inline_add false
                inline_edit false
            end    
        	field :title
            field :description, :text
            field :address
            field :footage
            field :work_pics
        end
    end
end

app/models/work_pic.rb
class WorkPic < ActiveRecord::Base
	belongs_to :work
	mount_uploader :photo, WorkPicPhotoUploader
	rails_admin do
        list do
        	field :id do
        		label "ID"
        	end	
            field :photo do
            	label "照片"
                pretty_value do
                    bindings[:view].tag(:img, { :src => bindings[:object].photo ,:width => '500'})
                end
                column_width 520
            end
        end  

        edit do
            field :photo
            field :work do
                visible false
            end

        end
    end	
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@works = Work.order("created_at desc").limit(3)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/qa_controller.rb
class QaController < ApplicationController
  def index
    @qas = Qa.all.order("id asc")
  end
  def show
    @qas = Qa.all.order("id asc")
    @qa = Qa.find(params[:id])  
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
  def index
     @works = Work.all
     @works = @works.where(:category_id => params[:category_id]) unless params[:category_id].blank?
     @works = @works.order("created_at desc").page params[:page]  

  	 @categories = Category.all
  end
  def show
    @work = Work.find(params[:id])
    @other_work = Work.all.shuffle[0..2]
    return redirect_to root_path if @work.blank?
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/qa_helper.rb
module QaHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/about_us/index.html.haml
= render partial: "main/header"
.main_container
	= image_tag('about_us_bg.jpg', :class => "main_bg")
	.row
		.col-md-12.content_bg.padding-bottom-20
			.custom_container
				.margin-20-0
					.row
						.col-lg-12.index_content_title.about_us_text_align.margin-20-0
							.line_left	
							ABOUT 關於明砌
							.line_right
						.col-lg-4	
						.col-lg-4
							明砌室內設計顛覆傳統設計師主導大權的刻板印象，結合了設計師的堅持與室內裝修的多年經驗，以人、空間、生活為本，站在客戶角度思考，建構出屋主心中的理想家園。
						.col-lg-4	
						.col-lg-12.index_content_title.about_us_text_align.margin-30-0
							TEAM 團隊介紹
						.team_introduce
							%p
								= image_tag("mouse.jpeg", :class =>"team_introduce_img", :align => "left")
								.team_introduce_title
									蕭幸均 / Ryan 設計師
								.team_introduce_educational_bg		
									%br
									· 復興商工 美工科
									%br
									· 內政部合格 室內裝修專業設計師
									%br
									· 一級 室內裝飾設計師
									%br
									%br
								.team_introduce_description	
									設計，必須從體會居住者的生活開始。居家規劃回歸居住者的真正需求即使用習慣，規劃出合宜的空間尺度及動線，使其住的舒適自在。材質的選擇與應用，相對也非常重要，因為那是影響空間風格與視覺效果的最重要元素。
							.team_introduce_line
						.team_introduce
							%p
								= image_tag("mouse.jpeg", :class =>"team_introduce_img", :align => "left")
								.team_introduce_title
									蕭幸均 / Ryan 設計師	
								%br
								· 復興商工 美工科
								%br
								· 內政部合格 室內裝修專業設計師
								%br
								· 一級 室內裝飾設計師
								%br
								%br
								設計，必須從體會居住者的生活開始。居家規劃回歸居住者的真正需求即使用習慣，規劃出合宜的空間尺度及動線，使其住的舒適自在。材質的選擇與應用，相對也非常重要，因為那是影響空間風格與視覺效果的最重要元素。
	= render partial: "main/footer"

app/views/contact_us/index.html.haml
= render partial: "main/header"
.main_container
    = image_tag('contact_us_bg.jpg', :class => "main_bg")
    .row
        .col-md-12.content_bg.padding-bottom-20
            .custom_container
                .margin-30-0
                    .row
                        .col-md-6.col-sm-6.left_context
                            .index_content_title_big.margin-top-10
                                明砌
                            .index_content_title    
                                室內設計工作室
                            .index_content_title_small
                                把您心中的想法與需求跟我們說吧
                                %br 歡迎您與我們聯絡！
                        .col-md-6.col-sm-6.text-left
                            .margin-top-20
                                = image_tag('location.jpg')
                                %span.margin-left-10  新北市土城區清水路 
                            .margin-top-20
                                = image_tag('email.jpg')
                                %span.margin-left-10  nose0821@gmail.com 
                            .margin-top-20
                                = image_tag('phone.jpg')
                                %span.margin-left-10  0925501962
                            .margin-top-20
                                %a{:href => "https://www.facebook.com/mc1506"}
                                    = image_tag('google.jpg')
                                %span.margin-left-10  
                                    %a{:href => "https://www.facebook.com/mc1506"} 線上詢問單  
                            .margin-top-20
                                %a{:href => "https://www.facebook.com/mc1506"}
                                    = image_tag('facebook.jpg')
                                %span.margin-left-10  
                                    %a{:href => "https://www.facebook.com/mc1506"} FB粉絲團
    = render partial: "main/footer"       

app/views/main/_footer.html.haml
.content_bg
    .footer_bg.text-center
        .footer_font
            明砌室內設計
        .footer_font    
            Tel：0925501962	Email：nose0821@gmail.com
        .footer_font
            Copyright © 2015 Allness. All rights reserved.

app/views/main/_header.html.haml
%nav.z2.navbar.navbar-default{:role => "navigation"}
    .container
        .navbar-header
            %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar    
            = link_to image_tag("logo2.png"), root_path, :class => "navbar-brand"
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
                %li= link_to "關於我們", about_us_path
                %li= link_to "最新消息", "https://www.facebook.com/profile.php?id=100010053691058&fref=ts", :target => "_blank"
                %li= link_to "作品集", work_path
                %li= link_to "服務項目", services_path
                %li= link_to "問與答", qa_path
                %li= link_to "聯絡我們", contact_us_path

app/views/main/index.html.haml
= render partial: "main/header"
.main_container
	= image_tag('index_bg.jpg', :class => "main_bg")
	.row
		.col-md-12.content_bg
			.custom_container
				.margin-20-0
					.row
						.col-md-12.text-center.index_content_title.margin-top-20
							.line_left
							%span	
								最新作品WOKS
							.line_right
					.row
						- @works.each do |work|		
							.col-md-4.col-sm-6	
								.index_list_box.margin-20-0.margin-bottom-40
									= link_to work_show_path(work) do
										.pic_box{:style => "background-image: url(#{work.first_photo.photo})"}
										.brief
											= work.title
											%br
											= "#{work.category.name} · #{work.address} · #{work.footage}坪"
									= link_to work_show_path(work) do		
										.hover_block
											%i.fa.fa-hand-pointer-o.fa-3
											%p See More	
	= render partial: "main/footer" 									

app/views/news/index.html.haml
最新消息

app/views/qa/index.html.haml
= render partial: "main/header"
.main_container
    = image_tag('service_bg.jpg', :class => "main_bg")
    .row
        .col-md-12.content_bg
            .custom_container
                .margin-20-0
                    .row
                        .col-md-4.text-left.index_content_title_big.margin-20-0
                            Questions
                            .text-left.q_bg.qa_size
                                - @qas.each do |qa|
                                    .line_hight
                                        = link_to qa_show_path(qa) do   
                                            = qa.id
                                            ="."
                                            = qa.question
                        .col-md-8.text-left.index_content_title_big.margin-20-0
                            Answer
                            .text-left.qa_size
                                = @qas.first.answer
    = render partial: "main/footer"
    

app/views/qa/show.html.haml
= render partial: "main/header"
.main_container
    = image_tag('service_bg.jpg', :class => "main_bg")
    .row
        .col-md-12.content_bg
            .custom_container
                .margin-20-0
                    .row
                        .col-md-4.text-left.index_content_title_big.margin-20-0
                            Questions
                            .text-left.q_bg.qa_size
                                - @qas.each do |qa|
                                    .line_hight
                                        = link_to qa_show_path(qa) do   
                                            = qa.id
                                            ="."
                                            = qa.question
                        .col-md-8.text-left.index_content_title_big.margin-20-0
                            Answer
                            .text-left.qa_size
                                = @qa.answer
    = render partial: "main/footer"

app/views/services/index.html.haml
= render partial: "main/header"
.main_container
	= image_tag('work_bg.jpg', :class => "main_bg")
	.row
		.col-md-12.content_bg
			.custom_container
				.margin-20-0
					.row
						.col-md-12.text-center.index_content_title.margin-top-20
							.line_left	
							Service 服務項目
							.line_right
					.row
						.col-md-4.col-sm-6.index_content_title.service_step	
							.service_title
								1.初步諮詢
								= image_tag("arrow.png", :class =>"arrow")
							.service_img								
								= image_tag("service1.jpg")
							.pic_line
							%p.text-left.service_step_detail
								1.電話諮詢
								%br
								2.丈量/拍照詳談需求
								%br
								3.討論平面配置，風格示意解說
								%br
								4.確認平面配置，工程估價擬估
								%br
								5.簽訂設計合約		
						.col-md-4.col-sm-6.index_content_title.service_step
							.service_title			
								2.設計階段
								= image_tag("arrow.png", :class =>"arrow")
							.service_img	
								= image_tag("service2.jpg")
							.pic_line
							%p.text-left.service_step_detail	
								1.第一次討論平/立面施工圖、建材
								%br
								2.第二次討論平/立面施工圖、確認建材
								%br
								3.確認平/立面施工圖，詳列工程估價
								%br
								4.簽訂工程合約
						.col-md-4.col-sm-6.index_content_title.service_step
							.service_title	
								3.施工階段
							.service_img	
								= image_tag("service3.jpg")
							.pic_line
							%p.text-left.service_step_detail	
								1.開工拜拜，排定工程進度表
								%br
								2.挑選窗簾/傢俱
								%br
								3.完工驗收、交屋
								%br
								4.拍攝完工照片
								%br
								5.交付完工手冊及保固書		
	= render partial: "main/footer"							

app/views/work/index.html.haml
= render partial: "main/header"
.main_container
	= image_tag('service_bg.jpg', :class => "main_bg")
	.row
		.col-md-12.content_bg
			.custom_container
				.margin-20-0
					.row
						.col-md-12.text-center.index_content_title.margin-20-0
							.line_left	
							WOKS 作品集
							.line_right
						.col-md-12.text-center.index_content_title.margin-top-20
							%span.category
								= link_to "全部", work_path	
							%span.divide_line	
								|	
							- @categories.each do |category|
								%span.category	
									= link_to work_path(:category_id => category.id) do
										= category.name	
								- if category != @categories.last
									%span.dsdsdsdsd	
										|						
						- @works.each do |work|		
							.col-md-4.col-sm-6.padding-0-20	
								.index_list_box.margin-top-20
									= link_to work_show_path(work) do
										.pic_box{:style => "background-image: url(#{work.first_photo.photo})"} 
									.index_content_title_small
										= "#{work.title}"
										%br
										= "#{work.address}|#{work.footage}坪"
									= link_to work_show_path(work) do	
										.hover_block2
											%i.fa.fa-hand-pointer-o.fa-3
											%p See More	
					.row
						.col-md-12.text-center.page
							= paginate @works
	= render partial: "main/footer"

app/views/work/show.html.haml
:ruby
    first_img = @work.first_photo.photo
= render partial: "main/header"
.main_container
    = image_tag('service_bg.jpg', :class => "main_bg")
    .row
        .col-md-12.content_bg
            .custom_container
                .work_show_margin
                    .row
                        .col-lg-8.col-md-8.col-sm-8
                            = link_to image_url(first_img), :class => "fancybox", :rel => "gallery1" do
                                %span.pic_box2{:style => "background-image: url(#{first_img})"}
                            - @work.work_pics.each do |work_pic|
                                - if work_pic != @work.work_pics.first
                                    = link_to image_url(work_pic.photo), :class => "fancybox", :rel => "gallery1" do
                                        %span.work_show_img2.pic_box3{:style => "background-image: url(#{work_pic.photo})"}  
                        .col-lg-4.col-md-4.col-sm-4.work_show_right_description.responsive_bottom        
                            .index_content_title
                                = @work.title
                            .work_show_line    
                            .category
                                = "分類：#{@work.category.name}"
                            .footage 
                                = "坪數：#{@work.footage}坪"
                            %br
                            %br    
                            .description    
                                = @work.description                 
                        .col-lg-12.text-left.index_content_title.margin-top-20
                            其他案例
                        .work_show_other_case_line
                        - @other_work.each do |other_work|     
                            .col-md-4.col-sm-6.padding-0-20  
                                .index_list_box.margin-20-0
                                    .pic_box{:style => "background-image: url(#{other_work.first_photo.photo})"}    
                                    .index_content_title_small
                                        = "#{other_work.title}"
                                        %br
                                        = "#{other_work.address}|#{other_work.footage}坪"
                                    .hover_block2                                  
                                        = link_to work_show_path(other_work) do
                                            %i.fa.fa-hand-pointer-o.fa-3
                                            %p See More
    = render partial: "main/footer"

 